generic_list:
  study_oid: S_DEFAULTS1
  study_identifier: protrait_test
  event_oid: SE_GENERIC_COLLECTION
  form_oid: F_PROTRAIT_GEN_2
  item_group_oid: IG_PROTR_GEN
  identifier_colname: GEN_IDNUMBER
  birthdate_colname: GEN_YEAR_BIRTH
  birthdate_isyear: TRUE
  gender_colname: GEN_GENDER
  item_prefix: I_PROTR_
  query: |
    prefix rr: <http://www.w3.org/ns/r2rml#>
    prefix ex: <http://example.com/ns#>
    prefix map: <http://mapping.local/>
    prefix sty: <http://purl.bioontology.org/ontology/STY/>
    prefix sio: <http://semanticscience.org/resource/SIO_>
    prefix foaf: <http://xmlns.com/foaf/0.1/>
    prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
    prefix xsd: <http://www.w3.org/2001/XMLSchema#>
    prefix ncit: <http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#>
    prefix roo: <http://www.cancerdata.org/roo/>
    prefix icd: <http://purl.bioontology.org/ontology/ICD10/>
    prefix skos: <http://www.w3.org/2008/05/skos#>
    prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
    prefix uo: <http://purl.obolibrary.org/obo/UO_>
    prefix time: <http://www.w3.org/2006/time#>

    SELECT DISTINCT
    ?GEN_IDNUMBER
    ?GEN_GENDER
    ?GEN_AGE
    ?GEN_TREAT_CENTER
    ?GEN_PLAN_COMP

#GEN_PLAN_COMP_DATE

   WHERE{


#gender
   OPTIONAL{
   ?Patient rdf:type ncit:C16960;
   roo:P100061 ?id.
   ?id roo:P100042 ?GEN_IDNUMBER.
   ?Patient roo:P100018 ?gender.
   ?gender roo:P100042 ?GenderValue.

   BIND(
   COALESCE(
   IF (?GenderValue = "V ", "2", 1/0),
   IF (?GenderValue = "M ", "1", 1/0),
   "9" )
   AS ?GEN_GENDER)
   }

#age
   OPTIONAL{
   ?Patient roo:P100016 ?age.
   ?age roo:P100042 ?GEN_AGE.
   FILTER (?GEN_AGE !=0)
   FILTER (?GEN_AGE !=1)
   FILTER (?GEN_AGE !=2)
   FILTER (?GEN_AGE !=3)
   FILTER (?GEN_AGE !=4)
   FILTER (?GEN_AGE !=5)
   FILTER (?GEN_AGE !=6)
   FILTER (?GEN_AGE !=7)
   FILTER (?GEN_AGE !=8)
   FILTER (?GEN_AGE !=9)
   FILTER (?GEN_AGE !=10)
   FILTER (?GEN_AGE !=11)
   FILTER (?GEN_AGE !=12)
   FILTER (?GEN_AGE !=13)
   FILTER (?GEN_AGE !=14)
   FILTER (?GEN_AGE !=15)
   FILTER (?GEN_AGE !=16)
   FILTER (?GEN_AGE !=17)
   FILTER (?GEN_AGE !=18)
       #FILTER (?GEN_AGE !=16)

        
   }

#treating centre
   OPTIONAL{
   ?Patient roo:P100039 ?treatingCentre.
   ?treatingCentre roo:local_value ?treatCentreValue.  } 
    
   BIND(
   COALESCE(
   IF (?treatCentreValue = "Maastro Clinic", "3", 1/0),
   IF (?treatCentreValue = "met name cochlea rechts van 14.4 naar 38.4 Gy (acceptabel) en brain Dmax van 46.6 naar 60.1 Gy (acceptabel)", "3", 1/0),
   IF (?treatCentreValue = "null", "0", 1/0),
   "9" )
   AS ?GEN_TREAT_CENTER)

    
#referring centre
#PTIONAL{
#Patient roo:P100039 ?treatingCentre.
#treatingCentre roo:referred_by ?refCentre.
#refCentre roo:P100042 ?GEN_REFER_CENTER.  }
    
    
#planning comparison
   OPTIONAL{
   ?Patient roo:P100024 ?radiotherapy.
   ?radiotherapy roo:has_planning_comparison ?plancomp. 
   ?plancomp roo:P100042 ?genplancomp.
   ?genplancomp roo:local_value ?GEN_PLAN_COMP1.}
    
   OPTIONAL{  
   ?Patient roo:P100024 ?radiotherapy.
   ?radiotherapy roo:has_planning_comparison ?plancomp.         
   ?plancomp roo:P100228 ?plancompdate.
   ?plancompdate roo:P100042 ?GEN_PLAN_COMP_DATE.}
        
   BIND(BOUND(?GEN_PLAN_COMP_DATE) as ?GEN_PLAN_COMP)  
    
    #IF(BOUND(?GEN_PLAN_COMP2), "?GEN_PLAN_COMP2", "unknown" as ?GEN_PLAN_COMP3)
        #COALESCE(?GEN_PLAN_COMP2, "unknown")
        #BIND(isBlank(?GEN_PLAN_COMP_DATE) AS ?GEN_PLAN_COMP3)     
        
#(COALESCE(?GEN_PLAN_COMP2, "0") as ?GEN_PLAN_COMP3)    
   BIND(
   COALESCE(
   IF (?GEN_PLAN_COMP = true, "1", 1/0),
   IF (?GEN_PLAN_COMP = false, "0", 1/0),
   "9" )
   AS ?GEN_PLAN_COMP)
    
   #FILTER regex(?GEN_AGE, "NULL").
   }

