PREFIX ncit:<http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#>
PREFIX roo: <http://www.cancerdata.org/roo/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT ?patient ?clinT ?clinN ?clinM ?overallStage ?diagnosisDate ?vitalStatusDate ?vitalStatus
WHERE {
	?patient a ncit:C16960 ;
        roo:P100008 ?diseaseObj ;
        roo:P100028 ?vitalStatusObj.

    # Vital status
	?vitalStatusObj roo:local_value ?vital_status.

    # Disease
    ?diseaseObj roo:P100025 ?overallStageObj ;
        roo:P100244 ?clinTObj ;
        roo:P100242 ?clinNObj ;
        roo:P100241 ?clinMObj ;
        roo:P100251 ?diagnosisDateObj.

    # Overall stage
    ?overallStageObj a ncit:C28108 ;
        roo:local_value ?stage.

    # Tstage
    ?clinTObj a ncit:C48885 ;
        roo:local_value ?t.
    
    # Nstage
    ?clinNObj a ncit:C48884 ;
        roo:local_value ?n.

    # Mstage
    ?clinMObj a ncit:C48883 ;
        roo:local_value ?m.

    # Diagnosis date
    ?diagnosisDateObj a ncit:C25164 ;
        roo:local_value ?date_of_diagnosis.
}